"project_id": "481295"                                                                                   #open project settings and go to API section 
"api_token": "6d801ae147c9811449d8e876bf436a674ed53206a7bd95d014b133dae6888658152de36aace8f2d9"          #open profile settings and go to API & SSO > New Token > create Token
"base_path": "."                                                                                         #path to your project directory on a local machine
"base_url": "https://crowdin.com"
"preserve_hierarchy": true

"files": [
  {
      "source": "public/locales/en/crowdin.json",                                          #source files filter
      "translation": "public/locales/%two_letters_code%/%original_file_name%",             #where translations are stored
      "update_option": "update_as_unapproved"                                              #
  }
]
